# $File: //ASP/tec/epics/selection/trunk/selectionTestApp/Db/Makefile $
# $Revision: #1 $
# $DateTime: 2023/01/10 23:12:38 $
# Last checked in by: $Author: starritt $
#

TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
#
DB += example_selection.template

#----------------------------------------------------
# Create and install (or just install) into <top>/crapi
#
CRAPI += example_selection.req

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

# end
